### ISSUE TITLE
camera problem

### ISSUE THREAD

**Issue by Kixbiles** [B0N3head/unity-fps-movement-controller#2]
the camera is insanely jittery, is there a fix?

**Comment by B0N3head** [comment]
That's quite odd, just to help debug this could you answer a few quick questions:

- What version of unity are you using?
- Are any of the variables/code changed, if so what?
- In what way do you mean jittery, does it only jitter when you move the mouse or is it constant?

**Comment by B0N3head** [comment]
I've been rather confused by this since you posted this as on unity 2019 through to 2022 has no issues. If you are still having this issue or found a fix plz feel free to comment. 
Cheers
