### ISSUE TITLE
Y axis jitter

### ISSUE THREAD

**Issue by Mellurboo** [B0N3head/unity-fps-movement-controller#3]
Unity 2022.2
The player object (not just the camera) seems to jitter up and down, I'm not sure why it may be a gravity issue but I cant seem to fix it

**Comment by Mellurboo** [comment]
Sorry I literally just found the fix
anyone reading this, the issue is because its constantly trying to set the player to the _Standing height_
if your player character doesn't match up with this then it means your standing height isn't accurate to your player controllers ACTUAL standing Hight, either make it shorter, taller, try and grab the height in code or just remove crouching

**Comment by B0N3head** [comment]
Sorry for the super late response 😅
Thanks for bringing this to my attention though, I'll try to make a fix soon to check if the height of the player and the standing height is the same.

**Comment by Mellurboo** [comment]
thanks bro!
