### ISSUE TITLE
Somethings wrong

### ISSUE THREAD

**Issue by Elijahwowl** [B0N3head/unity-fps-movement-controller#4]
hi, for some reason character is always moving forward and never stays still.

**Comment by B0N3head** [comment]
That's a little odd, just to help debug this issue, could you answer a few quick questions:

- What version of unity are you using?
- Are any of the variables/code changed, if so what?
- In what way do you mean moving forward. As in the way the camera is moving or in a set direction?

**Comment by Elijahwowl** [comment]
I'm using unity version 2021.3.26f1
I haven't changed any code
Its moving forward in the direction you look not in a set direction

Also it sometimes works fine but rarely and I tried removing the ground tag but it still didn't work.
